<div class="actions clearfix">
    <div class="btns">
        <a class="btn btn-primary" href="/comment/save" title="Criar Comment">
            Criar Comment
        </a>
    </div>
</div>
<h3>Lista de Comentários</h3>
<table class="table table-striped table-bordered">
    <thead>
    <tr>
        <th>Post Id</th>
        <th>Comentário</th>
        <th>Nome</th>
        <th>Email</th>
        <th>Site</th>
        <th>Data</th>
        <th>Opções</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach($comments as $comment):?>
        <tr>
            <td><?php echo $this->escapeHtml($comment->post_id);?></td>
            <td><?php echo $this->escapeHtml($comment->description);?></td>
            <td><?php echo $this->escapeHtml($comment->name);?></td>
            <td><?php echo $this->escapeHtml($comment->email);?></td>
            <td><?php echo $this->escapeHtml($comment->webpage);?></td>
            <td class="center">
                <?php
                echo $this->dateFormat(
                    \DateTime::createFromFormat('Y-m-d H:i:s', $comment->comment_date),
                    \IntlDateFormatter::SHORT,
                    \IntlDateFormatter::SHORT,
                    'pt_BR'
                );
                ?>
            </td>
            <td class="center">
                <a href="/comment/save/<?php echo $comment->id ;?>"
                   title="Editar">
                    Editar
                </a>
                <a href="/comment/delete/<?php echo $comment->id;?>"
                   rel="confirmation"
                   title="Deseja excluir este registro?">
                    Remover
                </a>
            </td>
        </tr>
    <?php endforeach;?>
    </tbody>
</table>